<?php
return [
    "migrationPrefix" => "2025_04_29_075641",
    "name" => "records",
    "columns" => [
        "id" => [
            "name" => "id",
            "type" => "BINARY",
            "nullable" => FALSE,
            "default" => "(UUID_TO_BIN(UUID()))",
        ],
        "user_id" => [
            "name" => "user_id",
            "type" => "BINARY",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#uuid",
            "config" => [
                "uuid" => TRUE,
            ],
        ],
        "string" => [
            "name" => "string",
            "type" => "VARCHAR",
            "nullable" => FALSE,
            "default" => NULL,
            "length" => 255,
        ],
        "email" => [
            "name" => "email",
            "type" => "VARCHAR",
            "nullable" => TRUE,
            "default" => NULL,
            "length" => 255,
            "comment" => "#email",
            "config" => [
                "email" => TRUE,
            ],
        ],
        "integer" => [
            "name" => "integer",
            "type" => "INT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#slider #min:1 #max:100",
            "config" => [
                "slider" => TRUE,
                "min" => 1,
                "max" => 100,
            ],
        ],
        "decimal" => [
            "name" => "decimal",
            "type" => "DECIMAL",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "n_p_w_p" => [
            "name" => "n_p_w_p",
            "type" => "BIGINT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#npwp",
            "config" => [
                "npwp" => TRUE,
            ],
        ],
        "datetime" => [
            "name" => "datetime",
            "type" => "DATETIME",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "date" => [
            "name" => "date",
            "type" => "DATE",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "time" => [
            "name" => "time",
            "type" => "TIME",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "i_p_address" => [
            "name" => "i_p_address",
            "type" => "VARCHAR",
            "nullable" => TRUE,
            "default" => NULL,
            "length" => 255,
            "comment" => "#ipaddress",
            "config" => [
                "ipaddress" => TRUE,
            ],
        ],
        "boolean" => [
            "name" => "boolean",
            "type" => "TINYINT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#boolean",
            "config" => [
                "boolean" => TRUE,
            ],
        ],
        "enumerate" => [
            "name" => "enumerate",
            "type" => "ENUM",
            "nullable" => TRUE,
            "default" => NULL,
            "options" => ["enable", "disable"],
        ],
        "text" => [
            "name" => "text",
            "type" => "TEXT",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "file" => [
            "name" => "file",
            "type" => "TEXT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#file",
            "config" => [
                "file" => TRUE,
            ],
        ],
        "image" => [
            "name" => "image",
            "type" => "TEXT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#image:jpg,jpeg,png",
            "config" => [
                "image" => "jpg,jpeg,png",
            ],
        ],
        "markdown_text" => [
            "name" => "markdown_text",
            "type" => "TEXT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#markdown",
            "config" => [
                "markdown" => TRUE,
            ],
        ],
        "w_y_s_i_w_y_g" => [
            "name" => "w_y_s_i_w_y_g",
            "type" => "TEXT",
            "nullable" => TRUE,
            "default" => NULL,
            "comment" => "#wysiwyg",
            "config" => [
                "wysiwyg" => TRUE,
            ],
        ],
        "latitude" => [
            "name" => "latitude",
            "type" => "DECIMAL",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "longitude" => [
            "name" => "longitude",
            "type" => "DECIMAL",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "created_at" => [
            "name" => "created_at",
            "type" => "TIMESTAMP",
            "nullable" => TRUE,
            "default" => "NOW()",
        ],
        "updated_at" => [
            "name" => "updated_at",
            "type" => "TIMESTAMP",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "created_by" => [
            "name" => "created_by",
            "type" => "BINARY",
            "nullable" => TRUE,
            "default" => NULL,
        ],
        "updated_by" => [
            "name" => "updated_by",
            "type" => "BINARY",
            "nullable" => TRUE,
            "default" => NULL,
        ],
    ],
    "foreignKeys" => [
        "user_id" => [
            "name" => "fk_records_users",
            "column" => "user_id",
            "referenced_table" => "users",
            "referenced_column" => "id",
        ],
    ],
    "indices" => [
        [
            "name" => "PRIMARY",
            "columns" => ["id"],
            "unique" => 0,
        ],
        [
            "name" => "created_at",
            "columns" => ["created_at"],
            "unique" => 0,
        ],
        [
            "name" => "fk_records_users",
            "columns" => ["user_id"],
            "unique" => 0,
        ],
    ],
    "primaryKey" => [
        "name" => "PRIMARY",
        "columns" => ["id"],
    ],
    "lang.en" => [
        "name" => "Records",
        "index_title" => "Records List",
        "new_title" => "New Record",
        "create_title" => "Add Record",
        "edit_title" => "Edit Record",
        "show_title" => "Show Record",
        "columns" => [
            "id" => "Id",
            "user_id" => "User Id",
            "string" => "String",
            "email" => "Email",
            "integer" => "Integer",
            "decimal" => "Decimal",
            "n_p_w_p" => "N P W P",
            "datetime" => "Datetime",
            "date" => "Date",
            "time" => "Time",
            "i_p_address" => "I P Address",
            "boolean" => "Boolean",
            "enumerate" => "Enumerate",
            "text" => "Text",
            "file" => "File",
            "image" => "Image",
            "markdown_text" => "Markdown Text",
            "w_y_s_i_w_y_g" => "W Y S I W Y G",
            "latitude" => "Latitude",
            "longitude" => "Longitude",
            "created_at" => "Created At",
            "updated_at" => "Updated At",
            "created_by" => "Created By",
            "updated_by" => "Updated By",
        ],
        "fields" => [
            "id" => "Id",
            "user_id" => "User Id",
            "string" => "String",
            "email" => "Email",
            "integer" => "Integer",
            "decimal" => "Decimal",
            "n_p_w_p" => "N P W P",
            "datetime" => "Datetime",
            "date" => "Date",
            "time" => "Time",
            "i_p_address" => "I P Address",
            "boolean" => "Boolean",
            "enumerate" => "Enumerate",
            "text" => "Text",
            "file" => "File",
            "image" => "Image",
            "markdown_text" => "Markdown Text",
            "w_y_s_i_w_y_g" => "W Y S I W Y G",
            "latitude" => "Latitude",
            "longitude" => "Longitude",
            "created_at" => "Created At",
            "updated_at" => "Updated At",
            "created_by" => "Created By",
            "updated_by" => "Updated By",
        ],
    ],
    "lang.id" => [
        "name" => "Records",
        "index_title" => "Tabel Records",
        "new_title" => "Tambah Record",
        "create_title" => "Tambah Record",
        "edit_title" => "Edit Record",
        "show_title" => "Lihat Record",
        "columns" => [
            "id" => "Id",
            "user_id" => "User Id",
            "string" => "String",
            "email" => "Email",
            "integer" => "Integer",
            "decimal" => "Decimal",
            "n_p_w_p" => "N P W P",
            "datetime" => "Datetime",
            "date" => "Date",
            "time" => "Time",
            "i_p_address" => "I P Address",
            "boolean" => "Boolean",
            "enumerate" => "Enumerate",
            "text" => "Text",
            "file" => "File",
            "image" => "Image",
            "markdown_text" => "Markdown Text",
            "w_y_s_i_w_y_g" => "W Y S I W Y G",
            "latitude" => "Latitude",
            "longitude" => "Longitude",
            "created_at" => "Created At",
            "updated_at" => "Updated At",
            "created_by" => "Created By",
            "updated_by" => "Updated By",
        ],
        "fields" => [
            "id" => "Id",
            "user_id" => "User Id",
            "string" => "String",
            "email" => "Email",
            "integer" => "Integer",
            "decimal" => "Decimal",
            "n_p_w_p" => "N P W P",
            "datetime" => "Datetime",
            "date" => "Date",
            "time" => "Time",
            "i_p_address" => "I P Address",
            "boolean" => "Boolean",
            "enumerate" => "Enumerate",
            "text" => "Text",
            "file" => "File",
            "image" => "Image",
            "markdown_text" => "Markdown Text",
            "w_y_s_i_w_y_g" => "W Y S I W Y G",
            "latitude" => "Latitude",
            "longitude" => "Longitude",
            "created_at" => "Created At",
            "updated_at" => "Updated At",
            "created_by" => "Created By",
            "updated_by" => "Updated By",
        ],
    ],
    "faker" => [
        "id" => NULL,
        "user_id" => "uuid()",
        "string" => "word()",
        "email" => "safeEmail()",
        "integer" => "randomNumber(5, true)",
        "decimal" => "randomFloat()",
        "n_p_w_p" => "randomNumber(15, true)",
        "datetime" => "dateTimeThisDecade()",
        "date" => "dateTimeThisDecade()",
        "time" => "time()",
        "i_p_address" => "localIpv4()",
        "boolean" => "boolean(0.5)",
        "enumerate" => "randomElement([\"enable\", \"disable\"])",
        "text" => "text(5)",
        "file" => NULL,
        "image" => NULL,
        "markdown_text" => "paragraph()",
        "w_y_s_i_w_y_g" => "randomHtml()",
        "latitude" => "randomFloat()",
        "longitude" => "randomFloat()",
        "created_at" => NULL,
        "updated_at" => NULL,
        "created_by" => NULL,
        "updated_by" => NULL,
    ],
    "seeder" => 10,
    "modelName" => "Record",
    "route" => "records",
    "controllerName" => "RecordController",
    "viewFolder" => "records",
    "policy" => [
        "index" => "table.index",
        "view" => "table.show",
        "create" => "table.create",
        "update" => "table.update",
        "delete" => "table.delete",
        "restore" => FALSE,
        "forceDelete" => FALSE,
    ],
    "action.index" => [
        "type" => "index",
        "paginate" => 10,
        "columns" => [
            "string",
            "email",
            "integer",
            "decimal",
            "n_p_w_p",
            "datetime",
            "date",
            "time",
            "i_p_address",
            "boolean",
            "enumerate",
            "latitude",
            "longitude",
        ],
    ],
    "action.create" => [
        "type" => "create",
        "uploadPath" => "records/{year}/{id}",
        "rules" => [
            "user_id" => ["nullable", "uuid", "exists:users,id"],
            "string" => ["required", "string"],
            "email" => ["nullable", "string"],
            "integer" => ["nullable", "numeric", "min:1", "max:100"],
            "decimal" => ["nullable", "numeric"],
            "n_p_w_p" => ["nullable", "numeric"],
            "datetime" => ["nullable", "date"],
            "date" => ["nullable", "string"],
            "time" => ["nullable", "date_format:H:i"],
            "i_p_address" => ["nullable", "string"],
            "boolean" => ["nullable", "numeric"],
            "enumerate" => ["nullable", "in:enable,disable"],
            "text" => ["nullable", "string"],
            "file" => ["nullable", "string"],
            "image" => ["nullable", "string"],
            "markdown_text" => ["nullable", "string"],
            "w_y_s_i_w_y_g" => ["nullable", "string"],
            "latitude" => ["nullable", "numeric"],
            "longitude" => ["nullable", "numeric"],
        ],
        "sections" => [
            "general" => [
                "title" => "Record",
                "fields" => [
                    "user_id" => [
                        "type" => "select",
                        "config" => [
                            "model" => "App\\Models\\Users",
                            "key" => "id",
                            "label" => "name",
                        ],
                        "col-lg" => "full",
                    ],
                    "string" => [
                        "type" => "text",
                        "config" => [
                            "required" => TRUE,
                        ],
                        "col-lg" => "full",
                    ],
                    "email" => [
                        "type" => "email",
                        "col-lg" => "full",
                    ],
                    "integer" => [
                        "type" => "slider",
                        "config" => [
                            "min" => 1,
                            "max" => 100,
                        ],
                        "col-lg" => "full",
                    ],
                    "decimal" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                    "n_p_w_p" => [
                        "type" => "npwp",
                        "col-lg" => "full",
                    ],
                    "datetime" => [
                        "type" => "datetime",
                        "col-lg" => "full",
                    ],
                    "date" => [
                        "type" => "date",
                        "col-lg" => "full",
                    ],
                    "time" => [
                        "type" => "time",
                        "col-lg" => "full",
                    ],
                    "i_p_address" => [
                        "type" => "ipaddress",
                        "col-lg" => "full",
                    ],
                    "boolean" => [
                        "type" => "checkbox",
                        "col-lg" => "full",
                    ],
                    "enumerate" => [
                        "type" => "select",
                        "options" => [
                            "enable" => "enable",
                            "disable" => "disable",
                        ],
                        "col-lg" => "full",
                    ],
                    "text" => [
                        "type" => "textarea",
                        "col-lg" => "full",
                    ],
                    "file" => [
                        "type" => "file",
                        "col-lg" => "full",
                    ],
                    "image" => [
                        "type" => "image",
                        "config" => [
                            "image" => "jpg,jpeg,png",
                        ],
                        "col-lg" => "full",
                    ],
                    "markdown_text" => [
                        "type" => "markdown",
                        "col-lg" => "full",
                    ],
                    "w_y_s_i_w_y_g" => [
                        "type" => "wysiwyg",
                        "col-lg" => "full",
                    ],
                    "latitude" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                    "longitude" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                ],
            ],
        ],
    ],
    "action.update" => [
        "type" => "update",
        "uploadPath" => "records/{year}/{id}",
        "rules" => [
            "user_id" => ["nullable", "uuid", "exists:users,id"],
            "string" => ["required", "string"],
            "email" => ["nullable", "string"],
            "integer" => ["nullable", "numeric", "min:1", "max:100"],
            "decimal" => ["nullable", "numeric"],
            "n_p_w_p" => ["nullable", "numeric"],
            "datetime" => ["nullable", "date"],
            "date" => ["nullable", "string"],
            "time" => ["nullable", "date_format:H:i"],
            "i_p_address" => ["nullable", "string"],
            "boolean" => ["nullable", "numeric"],
            "enumerate" => ["nullable", "in:enable,disable"],
            "text" => ["nullable", "string"],
            "file" => ["nullable", "string"],
            "image" => ["nullable", "string"],
            "markdown_text" => ["nullable", "string"],
            "w_y_s_i_w_y_g" => ["nullable", "string"],
            "latitude" => ["nullable", "numeric"],
            "longitude" => ["nullable", "numeric"],
        ],
        "sections" => [
            "general" => [
                "title" => "Record",
                "fields" => [
                    "user_id" => [
                        "type" => "select",
                        "config" => [
                            "model" => "App\\Models\\Users",
                            "key" => "id",
                            "label" => "name",
                        ],
                        "col-lg" => "full",
                    ],
                    "string" => [
                        "type" => "text",
                        "config" => [
                            "required" => TRUE,
                        ],
                        "col-lg" => "full",
                    ],
                    "email" => [
                        "type" => "email",
                        "col-lg" => "full",
                    ],
                    "integer" => [
                        "type" => "slider",
                        "config" => [
                            "min" => 1,
                            "max" => 100,
                        ],
                        "col-lg" => "full",
                    ],
                    "decimal" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                    "n_p_w_p" => [
                        "type" => "npwp",
                        "col-lg" => "full",
                    ],
                    "datetime" => [
                        "type" => "datetime",
                        "col-lg" => "full",
                    ],
                    "date" => [
                        "type" => "date",
                        "col-lg" => "full",
                    ],
                    "time" => [
                        "type" => "time",
                        "col-lg" => "full",
                    ],
                    "i_p_address" => [
                        "type" => "ipaddress",
                        "col-lg" => "full",
                    ],
                    "boolean" => [
                        "type" => "checkbox",
                        "col-lg" => "full",
                    ],
                    "enumerate" => [
                        "type" => "select",
                        "options" => [
                            "enable" => "enable",
                            "disable" => "disable",
                        ],
                        "col-lg" => "full",
                    ],
                    "text" => [
                        "type" => "textarea",
                        "col-lg" => "full",
                    ],
                    "file" => [
                        "type" => "file",
                        "col-lg" => "full",
                    ],
                    "image" => [
                        "type" => "image",
                        "config" => [
                            "image" => "jpg,jpeg,png",
                        ],
                        "col-lg" => "full",
                    ],
                    "markdown_text" => [
                        "type" => "markdown",
                        "col-lg" => "full",
                    ],
                    "w_y_s_i_w_y_g" => [
                        "type" => "wysiwyg",
                        "col-lg" => "full",
                    ],
                    "latitude" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                    "longitude" => [
                        "type" => "number",
                        "col-lg" => "full",
                    ],
                ],
            ],
        ],
    ],
    "action.show" => [
        "type" => "show",
        "sections" => [
            "general" => [
                "title" => "Record",
                "fields" => [
                    "id" => [
                        "col-lg" => "full",
                    ],
                    "user_id" => [
                        "col-lg" => "full",
                    ],
                    "string" => [
                        "col-lg" => "full",
                    ],
                    "email" => [
                        "col-lg" => "full",
                    ],
                    "integer" => [
                        "col-lg" => "full",
                    ],
                    "decimal" => [
                        "col-lg" => "full",
                    ],
                    "n_p_w_p" => [
                        "col-lg" => "full",
                    ],
                    "datetime" => [
                        "col-lg" => "full",
                    ],
                    "date" => [
                        "col-lg" => "full",
                    ],
                    "time" => [
                        "col-lg" => "full",
                    ],
                    "i_p_address" => [
                        "col-lg" => "full",
                    ],
                    "boolean" => [
                        "col-lg" => "full",
                    ],
                    "enumerate" => [
                        "col-lg" => "full",
                    ],
                    "text" => [
                        "col-lg" => "full",
                    ],
                    "file" => [
                        "col-lg" => "full",
                    ],
                    "image" => [
                        "col-lg" => "full",
                    ],
                    "markdown_text" => [
                        "col-lg" => "full",
                    ],
                    "w_y_s_i_w_y_g" => [
                        "col-lg" => "full",
                    ],
                    "latitude" => [
                        "col-lg" => "full",
                    ],
                    "longitude" => [
                        "col-lg" => "full",
                    ],
                    "created_at" => [
                        "col-lg" => "full",
                    ],
                    "updated_at" => [
                        "col-lg" => "full",
                    ],
                    "created_by" => [
                        "col-lg" => "full",
                    ],
                    "updated_by" => [
                        "col-lg" => "full",
                    ],
                ],
            ],
        ],
    ],
];