services:
  apache:
    build: .
    container_name: lara12_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - lara12_network

  postgres:
    image: postgres:latest
    container_name: lara12_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel12db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./storage/pg_data:/var/lib/postgresql/data
    networks:
      - lara12_network

networks:
  lara12_network:
    driver: bridge
